### PR TITLE
Add SatPy example notebook

### PR DESCRIPTION
**Pull request by djhoese**
This adds a basic overview of SatPy using some GOES-16 ABI data. I'm not a scientist so I made this to show off some of the features of SatPy rather than go into why the data was interesting. However, I based the data case I chose off a blog post by a colleague of mine who *is* a scientist and linked to that blog post.

Going to wait for the binder image to build and test this out on GCP now.

### CODE REVIEW

**Comment by rabernat** [comment]
This looks great, thanks @djhoese!

I'm not sure exactly what the CI is that @jhamman set up on this repo. I wouldn't worry too much about the failing test right now.

My one comment is that it would be nice to plot something. People like visuals. A demo with no plots is hard to get excited about.

**Comment by djhoese** [comment]
The "show" at the end displays an image. I can add a cartopy example I suppose. Right now this binder environment is showing a bug that has been so far random on my own machine. Hoping to finally track this down. I'll let you know when this is ready to merge.

I should note that the issue with plotting ABI data is that if you don't slice/stride it first you get a lot of data which the browser can't usually handle very well (or cartpy or geoviews). I'll see what I can do.

**Comment by rabernat** [comment]
> The "show" at the end displays an image.

Ah sorry I missed that! (I was looking for `plot` somewhere, as with matplotlib, pandas, and xarray).

**Comment by djhoese** [comment]
So I fixed a fairly important bug today in SatPy (see https://github.com/pytroll/satpy/pull/685 if you're curious). We probably won't end up releasing it until next week Monday so I think based on what I understand about binder's builds, this PR should wait until SatPy 0.14 is released.

**Comment by rabernat** [comment]
We are not in a big rush here. The real deadline is when the article is actually published. So please take your time!

**Comment by djhoese** [comment]
I also started a PR for satpy to make it easier to download test data so I'm hoping I can include that in here too to clean up the gcsfs usage: https://github.com/pytroll/satpy/pull/686

**Comment by jhamman** [comment]
The CI tests are fixed on master now.

**Comment by djhoese** [comment]
Ok thanks @jhamman. I'll rebase after the next satpy release.

**Comment by djhoese** [comment]
Oops I merged instead of rebased. I can work on fixing that if it really matters to you.

**Comment by jhamman** [comment]
@djhoese - merging is totally fine. We'll squash all the commits when we merge the PR anyway.

**Comment by djhoese** [comment]
Just tried testing this on the binderhub, hangs on saving to geotiffs so I may need to do some more debugging.

Edit: From what I can tell there aren't any dask customizations done on this repository. So it should be using the threaded scheduler as I expect. It worked locally.

**Comment by rabernat** [comment]
Can you import rasterio in the binder?

**Comment by djhoese** [comment]
Yes, it seems to be something with size of the data or maybe number of things being worked on at once in dask. I can force the threaded scheduler and remove certain computations from the image generation (remove certain enhancements) and then things seem to be ok. But even persisting the data in memory now seems to not work for these RGBs. Still investigating.

**Comment by djhoese** [comment]
I've finally found some time to investigate this further. I moved my notebook code to a script and ran it from a terminal on the jupyter hub instance. Using `dmesg` and I got:

```
[957951.001690] Memory cgroup out of memory: Kill process 3144177 (python) score 1869 or sacrifice child
[957951.011097] Killed process 3144177 (python) total-vm:2807964kB, anon-rss:1837724kB, file-rss:3056kB, shmem-rss:0kB
[957955.729287] oom_reaper: reaped process 3144177 (python), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

I'll try reducing the memory needed for the example to get it to stop hanging or being killed. Does anyone have an idea what the "Cgroups" memory limit is for Pangeo's binder?

**Comment by jhamman** [comment]
> Does anyone have an idea what the "Cgroups" memory limit is for Pangeo's binder?

I can tell you how much memory/cpu you're expected to have (14G). 

https://github.com/pangeo-data/pangeo-binder/blob/0052b2fc438cce3e8b7b594071f0c0d68b476561/helm-chart/pangeo-binder/values.yaml#L42-L47

**Comment by djhoese** [comment]
Interesting because based on the log message from `dmesg` I only have ~2.8GB allocated (my math is right I think).

**Comment by rabernat** [comment]
I'm preparing to resubmit the EOS comment piece and returning to this.

I really recommend we provide a _simple_ example with _low computational cost_ for this demo. It's important that everything work quickly and easily. This is more important than showing off advanced features.

Can we just bypass dask here?

**Comment by djhoese** [comment]
Not sure this was clear, but this example works perfectly fine now. The longest processing takes about 30 seconds to show the matplotlib figure at the end.

**Comment by rabernat** [comment]
Ah great! Will merge then?

**Comment by djhoese** [comment]
Sounds good to me.

**Pull request merged**
