### PR TITLE
SimPEG forward simulation example

### PR DESCRIPTION
**Pull request by lheagy**
- add a forward simulation example with SimPEG for airborne time domain electromagnetic data
- I would also like to add an inversion example with field data, but this gives an initial sampling 

image

### CODE REVIEW

**Comment by jhamman** [comment]
Very cool @lheagy - looks like we may also need `pymatsolver` in the environment?

**Comment by lheagy** [comment]
Okay, I think we are back in business, I was missing a couple requirements for the solver. Though... I think this example might use a bit too much RAM. I will work on trimming it down

https://mybinder.org/v2/gh/pangeo-data/open-source-geoscience/simpeg-example?filepath=Time_domain_electromagnetic_simulation.ipynb

**Comment by lheagy** [comment]
This is a more lightweight example that is good-to-go on my end. Please let me know if you have any questions / comments / suggestions for improvement.

**Comment by rabernat** [comment]
This is great!

I would just try to rename following the conventions recommended by @jhamman in #4.

**Pull request merged**
